# Generated by Django 3.1.2 on 2020-10-12 13:00

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201012_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
